### ISSUE TITLE
Feature Request: focus the input of the commit message

### ISSUE THREAD

**Issue by ChristopherGouin** [rioukkevin/vscode-git-commit#10]
Is it possible that the validation of the last variable of the commit message, set the focus on the vscode input commit message.

to avoid adding lines in the current file thinking to validate the commit directly

![image](https://user-images.githubusercontent.com/31845587/115214567-ee014800-a102-11eb-9345-f160e34ddfbb.png)

**Comment by rioukkevin** [comment]
I work on in next days ;)

**Comment by rioukkevin** [comment]
Done 😉
