### ISSUE TITLE
Can't define own templates

### ISSUE THREAD

**Issue by stanislasbdx** [rioukkevin/vscode-git-commit#12]
I set my templates in the config, but when I "generate" a commit message, my custom template doesn't appear.

```json
"vscodeGitCommit.variables": {
    "prefix": "keke",
    "aliases": [
      {
        "label": "🚀 workspace upgrade",
        "detail": "Select when a workspace package is upgraded",
        "key": "5993179",
      },
      {
        "label": "🌈 style",
        "key": "9355052",
        "detail": "Select when beautify or style changes"
      }
    ]
}
```

![image](https://user-images.githubusercontent.com/17954501/117140910-37fa5700-adae-11eb-8264-4d9f109f0850.png)

**Comment by rioukkevin** [comment]
Currently publishing a new version (2.1.0) that fix it, sorry for the inconvenience, it will auto migrate settings to be compliant with old ones
