### ISSUE TITLE
The plugin does not work in the latest vscode

### ISSUE THREAD

**Issue by zhangzhenfei** [rioukkevin/vscode-git-commit#13]

**Comment by zhangzhenfei** [comment]
![Uploading image.png…]()

**Comment by zhangzhenfei** [comment]
![image](https://user-images.githubusercontent.com/6110215/117525336-53ef3a00-aff4-11eb-950f-10823614fe84.png)

**Comment by rioukkevin** [comment]
I can not reproduce the bug in my environment, does anyone else have this bug ?

**Comment by rioukkevin** [comment]
I close the issue but I'm open to reopen it if I have more informations to reproduce the bug ;)

**Comment by zhangzhenfei** [comment]
> I close the issue but I'm open to reopen it if I have more informations to reproduce the bug ;)

the bug is fixed~

**Comment by rioukkevin** [comment]
Oh Nice, thanks for feedback :wink:
