### ISSUE TITLE
Extension not working... Only changes cursor position

### ISSUE THREAD

**Issue by LukasWallisch** [rioukkevin/vscode-git-commit#14]
i'm using VS-Code
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-77-generic (Ubuntu 20:04)

and your Extension in version 2.1.0 if i press the message icon or the keyCombi nothing happens except the cursor jumping from the Commitmessagefield to the Codeeditor or vice versa -.-

**Comment by rioukkevin** [comment]
Hi, I'm not sure about what happen, can you send me your settings.json (only part for the extension) that's possibly something here

**Comment by LukasWallisch** [comment]
`"vscodeGitCommit.variables": {
    "prefix":"webphone_ui #13991"
    },
    "vscodeGitCommit.template": [
        "{prefix}  {message}"
    ]`

**Comment by rioukkevin** [comment]
Oki, I understand, I need to update the extension, for "vscodeGitCommit.variables" -> "prefix" the extension do not support custom string today, I let the issue open and work on it.
What you can do is : 
```json
{
  "vscodeGitCommit.variables": {
     "prefix": [
        {
           "label":"webphone_ui #13991",
           "key":"12345"
        }
     ]
  }
}

**Comment by LukasWallisch** [comment]
thx a lot for the fast answer!

this is working now :)

maybe a error-message would be a good idea? then

**Comment by rioukkevin** [comment]
Yep, I look how to add it 😉 
Thanks for feedback
