### ISSUE TITLE
没法用，以前可以选的，现在直接弹这个了

### ISSUE THREAD

**Issue by Hemingway-ai** [rioukkevin/vscode-git-commit#15]
![image](https://user-images.githubusercontent.com/52399183/124413420-29ff8d00-dd83-11eb-932c-6234a0469e81.png)

**Comment by rioukkevin** [comment]
Sorry, I speak English and French only, with google traduction I don't understand the meaning of your issue title

**Comment by LuckyHookin** [comment]
After installation, I can't see the commit option, like this:
![gif](https://user-images.githubusercontent.com/45350455/126424032-46254f1d-5668-4d67-89be-2db306424fcc.gif)
I don't know if it's a bug. 

Thank you!

----
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.58.2 (user setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
date: 2021-07-14T22:10:15.214Z (6 天前)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by rioukkevin** [comment]
Thanks, I understand you can create the config option for `vscodeGitCommit.variables` to 
```
{
  "prefix":"<one_option>"
}
```
replace <one_option> by 'keke','angular' or 'semantic' as you prefer 😉 [more details](https://github.com/rioukkevin/vscode-git-commit#3-use-select-or-text-for-each-variables-vscodegitcommitmessagetemplate)

In next days, I create a default configuration and update doc if you can wait a bit

**Comment by rioukkevin** [comment]
Hi,

I update the extension with new default settings and a clearer doc 😉 

PS: I deploy a new version (3.0.0) minutes ago

Have a nice day and be happy
