### ISSUE TITLE
Can We have Configuration like shown in demo video ?

### ISSUE THREAD

**Issue by VimLeSai** [rioukkevin/vscode-git-commit#16]
In Demo video there is already configured properly and it should be the default config or you should provide that config in doc also

**Comment by rioukkevin** [comment]
Thanks for feedback, I make a new version in next days to make a default configuration like in video

**Comment by VimLeSai** [comment]
@rioukkevin hi, i really wanted to use the  extension the way it works in the video.

**Comment by rioukkevin** [comment]
I'm sorry, I'm a bit overbooked this month, you can use this setting while the new version is in development 
```json
"vscodeGitCommit.variables": {
  "prefix":"keke"
}
```

**Comment by IOLOII** [comment]
> 

what's this line running principle?
I just add this, then got some dropdown options 😂. **Before this, I don't know how to add dropdown options,**  so could you please add more comment about how to use it, `just like your screenshot gif show` , tks

**Comment by IOLOII** [comment]
> I'm sorry, I'm a bit overbooked this month, you can use this setting while the new version is in development
> 
> ```json
> "vscodeGitCommit.variables": {
>   "prefix":"keke"
> }
> ```

what's this line running principle?
I just add this, then got some dropdown options 😂. **Before this, I don't know how to add dropdown options** , so could you please add more comment about how to use it,  `just like your screenshot gif show` , tks

**Comment by rioukkevin** [comment]
> > I'm sorry, I'm a bit overbooked this month, you can use this setting while the new version is in development
> > ```json
> > "vscodeGitCommit.variables": {
> >   "prefix":"keke"
> > }
> > ```
> 
> what's this line running principle? I just add this, then got some dropdown options 😂. **Before this, I don't know how to add dropdown options** , so could you please add more comment about how to use it, `just like your screenshot gif show` , tks

I work on an UI to generate variable settings 😉 

in the default template ("{prefix} ({scope}): {message}" there is three variables, "prefix" "scope" and "message" so in the settings `vscodeGitCommit.variables` you can choose the content of each variables of the template:

In this case, the preset named "keke" is applied to the variable "prefix" if you want to customize which options you get in the select you can follow this documentation https://github.com/rioukkevin/vscode-git-commit#3-use-select-or-text-for-each-variables-vscodegitcommitmessagetemplate 

I'm not sure this is clear, feel free to send me another message if not 😉

**Comment by rioukkevin** [comment]
Hi,

I make default the settings I use in the demo GIF 😉 

PS: I deploy a new version (3.0.0) minutes ago

Have a nice day and be happy
