### ISSUE TITLE
Encountered annoying noise in the configuration file

### ISSUE THREAD

**Issue by gwsbhqt** [rioukkevin/vscode-git-commit#17]
No matter what you fill in or even if you don't fill in there will be noise, this is very frustrating.

![image](https://user-images.githubusercontent.com/16471930/133394941-4efdc852-7583-4497-94d6-ab003fb7643f.png)

**Comment by rioukkevin** [comment]
Thanks for the feedback, I work on to disable this noise

**Comment by rioukkevin** [comment]
Hi,

I update the settings validation to avoid this noise in configuration 😉 

PS: I deploy a new version (3.0.0) minutes ago

Have a nice day and be happy
