### ISSUE TITLE
command 'vscodeGitCommit.setMessage' not found

### ISSUE THREAD

**Issue by davidsmorais** [rioukkevin/vscode-git-commit#18]
Hey :wave: 

I'm getting this message after a fresh install.
![image](https://user-images.githubusercontent.com/22729436/147014095-ee5b6bfe-308b-42b7-96aa-6fea5250f320.png)

This is my config :point_down: 
```
  "vscodeGitCommit.insertMode": "Concatenate",
  "vscodeGitCommit.variables": {
    "prefix": "alpha",
    "aliases": [
      {
        "key": "321",
        "label": "🚀 Feature",
        "detail": "New feature"
      }
    ]
  },
  "vscodeGitCommit.template": ["{prefix}: {message}"],
```

**Comment by rioukkevin** [comment]
Hi,
this is possibly due to the value of the variable "prefix", all predefined collections are:
- keke
- semantic
- angular
- alpha**8**

Could you try with and give me a feedback ?
```json
  "vscodeGitCommit.variables": {
    "prefix": "alpha8",
    ...
  },
```

You're pointing a good aspect of the extension, I have to work on feedbacks (Error messages,...)

**Comment by davidsmorais** [comment]
Hey, thanks for the fast reply. That worked.

What's the difference between these prefixes ?

**Comment by rioukkevin** [comment]
Each of this four prefix are following differents norms

Semantic is from Semantic commit https://www.conventionalcommits.org/en/v1.0.0/ 
Angular is prefixes used by lot of people when working on Angular (not angularJS) https://gist.github.com/brianclements/841ea7bffdb01346392c 
Keke is prefixes I used every day in my personnals projects
Alpha8 is prefixes that are used in the enterprise where I work all days

😉

**Comment by davidsmorais** [comment]
Thank you for the clarification. Could be worth it to add it to the README if it's not there already :smile: 

Thanks again and congratz on the extension :clap:

**Comment by rioukkevin** [comment]
Planning to add it in a web doc, I work on a generator UI for settings and a web doc to explain more clearly what is possible with the extension, thanks for your feedback
