### ISSUE TITLE
Utiliser les prefix git flow 

### ISSUE THREAD

**Issue by DimitriSauvage** [rioukkevin/vscode-git-commit#2]
Base configuration should be the git flow prefix : 

- feature
- hotfix
- release
- develop

You can also keep your own prefix, because they can be useful.

Good job guy !

**Comment by rioukkevin** [comment]
I add selector in settings
GIT Flow 
Angular
SemanticCommitMessage

If more to add, please open an issue 😃

**Have a nice day and be happy**

**Comment by rioukkevin** [comment]
So i search for documentation about it but everything is speaking about name in branch
like following : 
- bugfix
- config
- feature
- hotfix
- init
- release
- support
- version

Are you sure it's about commit prefix ?

If Yes, I commit with the full selection of prefix, if  not, i don't commit it 😉 

source: https://github.com/petervanderdoes/gitflow-avh/wiki#reference

**Comment by rioukkevin** [comment]
With settings if needed you can add your own prefix 😃

**Comment by rioukkevin** [comment]
I forgot documentation for prefix selector, I add it on next release
