### ISSUE TITLE
Is there a way to include the current branch in the prefix?

### ISSUE THREAD

**Issue by mattcockrell** [rioukkevin/vscode-git-commit#20]

**Comment by rioukkevin** [comment]
Hi, today not, but I can add it to features of next release ;) 
Firstly, I will look if it's possible todo
If yes, I develop it and release it on next update

**Comment by mattcockrell** [comment]
thanks!

**Comment by katunilya** [comment]
@mattco18 Hi!

Just not to duplicate the issue I want to know if by `include the current branch in the prefix` you mean something like issue number this branch is related to?

My team often links commit to issue as we are feature-oriented and simple template like `{message} (#{issue})` does it's job, but maybe it will be useful to include some shortcut for that.

If it's not what you mean I can propose another issue. @rioukkevin what do you think?

**Comment by rioukkevin** [comment]
Hi @katunilya 
Sorry for the late reply, I already thought of a predefined part of the template for a use case like yours but I'm leaving the idea in the trash, it adds a lot of complexity to the extension, today , it gets bigger and bigger with every update and I don't want to add another level of complexity, at the moment I don't accept your proposal, but if in the future a lot of people request , I could think about it ;) 

What I understand of @mattco18 feature request is the ability to insert the name of the current branch in the commit message

**Comment by katunilya** [comment]
@rioukkevin, thanks for your reply!

I appreciate your desire to keep extension clean, simple and avoid over-engineering. I think feature that includes current branch name in commit message covers some cases of mine, so it will work for me.

Thx for such a good tool by the way 👍

**Comment by boekhoffm** [comment]
Upvoting to get the branch name in the commit message by defaulit - I see v3.0.1 in the description of the extension - is 3.0.2 available yet, because February is mentioned above.

**Comment by rioukkevin** [comment]
Hi @boekhoffm,

I'm sorry, I don't have time to work on the extension last month, I have a bit of work for this month, but this summer is normally less busy, I can work on in July, I think 😉 

Have a nice day,
Kevin

**Comment by 365kim** [comment]
Can't wait for this feature. 👍👍👍

**Comment by rioukkevin** [comment]
Working on it tomorrow 😉 releasing it too

**Comment by boekhoffm** [comment]
No worries I can type/paste it, I'm just lazy

By the way, it's not obvious to a lazy reader that the shortcut is
ctrl+alt+enter

**Comment by rickvian** [comment]
cool extension, but i find it hard to understand the documentation at glance,
how do i add branch name?

**Comment by rioukkevin** [comment]
Yes, that's the feedback I got from many peoples, I work on a full rework of the extension with a settings shared between CLI, VSCode and any other thing that we can imagine, but it's a lot of dev, i'm not familiar with collaboration and at this time my time to work on it is very limited, I start in a new organisation and start working for a streamer too :/
