### ISSUE TITLE
(Feature) Load settings from repo

### ISSUE THREAD

**Issue by jamessampford** [rioukkevin/vscode-git-commit#22]
I haven't seen that it is currently possible, but would be great if the settings for this could be loaded from the repo currently being worked on

For example, if there was a file in the root called `.committemplate` this could override any local settings with the contents of this file

Why? Every member of a team could use this plugin and the commit message templates would be consistent (and up to date) rather than needing to ask everyone to update the settings within the plugin each time the templates need to be updated

This would be a bit like how .editorconfig works (https://editorconfig.org)

**Comment by rioukkevin** [comment]
Hi,

You can use a the file `vscode/settings.json` in the folder opened with vscode, it override settings for vscode locally 😉 

Have a nice day,
Kevin

**Comment by jamessampford** [comment]
> You can use a the file `vscode/settings.json` in the folder opened with vscode, it override settings for vscode locally 😉

Aren’t these all the settings for vscode though? The suggested feature is just for the settings for the plug-in to standardise commit messages for the team to use, by loading the settings from the repo currently being worked on

This is probably the same way that I think you use `.prettierrc` for in the repo root, with the settings for prettier updated based on these, rather than what is locally set within the vscode settings

**Comment by maxisam** [comment]
I think this is a good idea. because there are lots of personal settings in `vscode/settings.json` I think it is not ideal force other team member to have one settings
