### ISSUE TITLE
Can we define some variables as optional?

### ISSUE THREAD

**Issue by luthor77** [rioukkevin/vscode-git-commit#26]
I want to just click enter on a free text field, when I don't want to provide some info. like this config:

`  "vscodeGitCommit.template": [
    "{feat}({scope}): {message}",
    "{body}",
    "{breakingIssue}",
    "Closes {closesIssue}"
  ]
`

I want to be able to skip body and the rest some times. but if I hit "enter" the extension cancels the message:
![image](https://user-images.githubusercontent.com/31356395/179290499-0401cbf7-6d6e-4449-a307-25c6314efd9d.png)

**Comment by rioukkevin** [comment]
Can you give me your variables config please ? 😉 I think I can respond to your request, but i need to be sure of what you need

**Comment by luthor77** [comment]
@rioukkevin Sorry for the wait, my variables are like this: 
![image](https://user-images.githubusercontent.com/31356395/179535718-4decc7f4-2174-4485-a597-cc6df0f17f6a.png)

The rest are free text, and I want them to be optional.

One another feature I would like is to be able to pass a label to the variables, specially the free text ones.

**Comment by rioukkevin** [comment]
Oki thank you for feedback, no problem for delay, I’m not example of quick answer 😉 

I find the problem of free inputs, normally it can take no value but there is a bug so I’m gonna fix it ASAP

for thé feature request I have to imagine how to do it without breaking everyone config so it take more time but I’m on it too

**Comment by luthor77** [comment]
Ok, thank you for your response. I'll wait for the fix.

About the feature I think something like this could work, where when we don't pass, it assumes the default:
```
"vscodeGitCommit.variablesLabel": {
  "<variable_name>": "label",
}
```
But it's just a suggestion I don't really know how it's made, I'll wait for this too.

**Comment by rioukkevin** [comment]
<img width="883" alt="image" src="https://user-images.githubusercontent.com/45003887/179764494-d946b42a-b744-4fab-b7c6-8a5f82a9873b.png">

Is something like that ok ? 

I made the functionnality, I have to update config generator and documentation for the feature

The bug, was a mistake of me, i fix it, I release it with the feature 😉

**Comment by rioukkevin** [comment]
I'm sorry, I don't wait for feedback, but if needed, i can update the extension again 😉 v3.0.3 is now released

**Comment by luthor77** [comment]
@rioukkevin It's perfect now, thanks for your work.
