### ISSUE TITLE
Cannot read properties of undefined (reading 'repository')

### ISSUE THREAD

**Issue by ly-sniper** [rioukkevin/vscode-git-commit#28]
when ctrl+alt+enter on windows, a warning message appear at the bottom-right corner
```js 
Cannot read properties of undefined (reading 'repository')
```

My vscode Info:
版本: 1.70.0 (user setup)
提交: da76f93349a72022ca4670c1b84860304616aaa2
日期: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by swq123459** [comment]
vscode更新到1.70，就坏掉了

**Comment by vagabondHustler** [comment]
VSC 1.7 broke something, temporary fix for me is to run 1.69 https://code.visualstudio.com/updates/v1_69

**Comment by rioukkevin** [comment]
Hi, I update my VSCode version and try ;)

**Comment by rioukkevin** [comment]
I'm reading the detailed release note to understand if it's a bug or a change in the VSCode Api, I send you messages when I found something 😉

**Comment by rioukkevin** [comment]
I'm currently uploading a fix to vscode marketplace, the new version (v3.1.0) is available in minutes, thank you all for your feedback i was a bit late on my vscode version and don't see there is a bug since last update

Can you you give me a feedback if it fix it for you ?

**Comment by vagabondHustler** [comment]
> I'm currently uploading a fix to vscode marketplace, the new version (v3.1.0) is available in minutes, thank you all for your feedback i was a bit late on my vscode version and don't see there is a bug since last update
> 
> Can you you give me a feedback if it fix it for you ?

Works for me now on vsc 1.7, amazing, thank you!

**Comment by T-MAC-T** [comment]
it's working, tkx again!
