### ISSUE TITLE
Add custom prefix in the selection

### ISSUE THREAD

**Issue by DimitriSauvage** [rioukkevin/vscode-git-commit#3]
# Context :
After click on the custom extension button in the source control tab, you can select a prefix.

# Need : 
To have a better experience, it should be great if we could add a prefix directly in the selection.

# Possible solutions :
1. Add a button to redirect to the settings
2. Directly add a prefix from the selection modal if possible.

Thanks guy

**Comment by rioukkevin** [comment]
Working on

**Comment by rioukkevin** [comment]
I'm working on but new priorities are coming from my new job 😉 Please be patient 😃

**Comment by rioukkevin** [comment]
I work on later, I have to learn how to update settings programmaticaly to use it

**Comment by rioukkevin** [comment]
This feature is partially obsolete, if someone else claim it, I will add it but it take lot of time to do 😉
