### ISSUE TITLE
最新的vscode生成的commit message位置不对

### ISSUE THREAD

**Issue by zhangzhenfei** [rioukkevin/vscode-git-commit#31]
最新的vscode生成的commit message位置不对，跑到其他存储库条目上了

**Comment by rioukkevin** [comment]
How many repo do you have ? 

VSCode API has changed last month so, I probably made a mistake while updating, I have to test a PR first and then work on the fix for this 😉

**Comment by rioukkevin** [comment]
Does someone else have the same issue ?
