### ISSUE TITLE
Change Default Commit Options

### ISSUE THREAD

**Issue by W1L7dev** [rioukkevin/vscode-git-commit#36]
Hey! I think it would be cool if you can edit default commit options. Idk if it's clear, but here's what i call "commit options"
![image](https://user-images.githubusercontent.com/83970923/204029322-8d5252de-1eca-4f6d-96d2-b6a09424b221.png)
Idk if it's already possible, but if it's not, can you add it?

**Comment by rioukkevin** [comment]
Hi, you can define your own options in VSCode settings.
You can use this UI https://gcm-config.netlify.app/configurator or do it manually to configure it 😉

**Comment by W1L7dev** [comment]
I did not find it easy to use and I was kinda confused. It is not well explained. Can you tell me how to use it?

**Comment by rioukkevin** [comment]
> I did not find it easy to use and I was kinda confused. It is not well explained. Can you tell me how to use it?

Sorry for delay i just change job, It's difficult to explain, I try first to simplify but with time I see that it's more complicated than before

**Comment by W1L7dev** [comment]
Maybe making it simplee by giving them more drscriptive title such as "edit commit option"  and "add new commit option"

**Comment by rioukkevin** [comment]
I keep in mind for when I'll have more time to refactor the whole project

**Comment by W1L7dev** [comment]
👍

**Comment by ahmad4zan** [comment]
this is how i change the default values
```
"vscodeGitCommit.variables": {
        "prefix": [
            {
                "label": "✨feature",
                "detail": "(new feature for the user, not a new feature for build script)"
            },
            {
                "label": "🐛fix",
                "detail": "(bug fix for the user, not a fix to a build script)"
            },
            {
                "label": "📝docs",
                "detail": "(changes to the documentation)"
            },
            {
                "label": "♻️refactor",
                "detail": "(refactoring production code, eg. renaming a variable)"
            },
            {
                "label": "🎨style",
                "detail": "(formatting, missing semi colons, etc; no production code change)"
            },
            {
                "label": "✅test",
                "detail": "(adding missing tests, refactoring tests; no production code change)"
            },
            {
                "label": "👷build",
                "detail": "(deploy and build)"
            },
        ],
        "feat": "alpha8"
    }
```

<img width="610" alt="Screenshot 2024-04-24 at 9 16 00 AM" src="https://github.com/rioukkevin/vscode-git-commit/assets/2517241/12d1fdf9-620b-4300-9feb-37eb6db1e40f">

**Comment by W1L7dev** [comment]
thanks!
