### ISSUE TITLE
More than one repo, commit text in first one

### ISSUE THREAD

**Issue by m3koenig** [rioukkevin/vscode-git-commit#39]
Hi :)

If you have more than one repo opend in VS Code, the commit will set into the first repo:

![image](https://user-images.githubusercontent.com/9989457/233986206-0b761085-c413-4f8a-9128-d5a287a767ba.png)

**Comment by lucasrodes** [comment]
Hi, I am encountering a similar issue. Instead of assigning the message to the first repo, it gives it to the second one for some reason in my case.

@m3koenig did you find any workaround to assign it to a particular repository?

**Comment by m3koenig** [comment]
Nope. But in another project I got your explained behaviour also. Copy the message and paste it into the other repo but I hope there will be a fix someday 😅

**Comment by YorickColeu** [comment]
The commit message appears to be associated with the module whose name is the furthest in alphabetical order.

**Comment by diogo-rossi** [comment]
> The commit message appears to be associated with the module whose name is the furthest in alphabetical order.

Seems to be the case. 

In my case I have a subrepo (submodule) named "wiki", and the main project's name starts with "M".

The message appear in the "wiki" repo git commit message box.
