### ISSUE TITLE
Cannot read properties of undefined (reading 'rootUri')

### ISSUE THREAD

**Issue by Charlie50503** [rioukkevin/vscode-git-commit#45]
when ctrl+alt+enter on windows, a warning message appear at the bottom-right corner

```
Cannot read properties of undefined (reading 'rootUri')
```

![image](https://github.com/rioukkevin/vscode-git-commit/assets/61115012/3b42789d-ccd5-4aa4-abe8-f0cd45d45b2e)

![image](https://github.com/rioukkevin/vscode-git-commit/assets/61115012/c37e3cbf-72e1-4dfa-bebe-bf6110fef612)

**Comment by jasonaviandres** [comment]
having the same issue here

**Comment by diogo-rossi** [comment]
Duplicates of #43

**Comment by rioukkevin** [comment]
Hiii, sorry for delay, I just publish the version with the fix from @Diogo-Rossi so it will be available soon
