### ISSUE TITLE
Prefix added to commit message when escape pressed

### ISSUE THREAD

**Issue by DuelMonster** [rioukkevin/vscode-git-commit#5]
Replication Steps:

Scenario 1:
1. Click the extension button or use the Ctrl+Alt+Enter shortcut
2. Press the escape key twice to cancel
3. A semicolon ( : ) will be entered into the commit message

Scenario 2:
1. Click the extension button or use the Ctrl+Alt+Enter shortcut
2. Select a prefix
3. Press the escape key to cancel
4. The previously selected prefix will be entered into the commit message

**Comment by rioukkevin** [comment]
Hmmm yeah i don't handle cancel at this time, I'll add it in v1.1.2  in weeks :wink:

**Comment by rioukkevin** [comment]
I Handle it, you can upgrade your extension version 😉
