### ISSUE TITLE
Commit in multi-repo workspace adds message to wrong repository

### ISSUE THREAD

**Issue by Duncank** [rioukkevin/vscode-git-commit#6]
Steps to reproduce:

1. open a workspace with multiple repositories in it.
2. press the 'git prefix emote' button
3. enter a message.

What I expected:  
I clicked the button on the first repository, and I expected the commit message to show up there. 

What happened:
The commit message was entered into the text field of the second repository: 

![image](https://user-images.githubusercontent.com/719365/98348871-8f935200-2019-11eb-8184-0dadd7728bd9.png)

I'm using vscode 1.50.1 on windows 10.

**Comment by rioukkevin** [comment]
Okay, I work on it, Thanks for feedback

**Comment by rioukkevin** [comment]
That's good, I publish version 1.1.4 with multi repository feature 😃
