### ISSUE TITLE
Feature Request: Being able to specify template variables presets

### ISSUE THREAD

**Issue by TheThirdRace** [rioukkevin/vscode-git-commit#7]
### Feature Request
I really like how you can define new variables to customize the `vscodeGitCommit.messageTemplate`.

It's really simple, you type a new variable in the template (ex: {scope}) and you get a prompt to fill it. It also gives the extension a flexibility no other vscode "commitizen" extension has.

**The only thing missing is to be able to give presets for those variables.**

### Example

Let's take the example mentioned earlier, when I defined a custom variable {scope}.

What I would like is be able to define values for that variable in settings.json.

Something like:
```
"vscodeGitCommit.messageTemplateVariables": {
    scope: [
        "security",
        "infrastructure",
        "CI",
    ]
}
```

And then, instead of prompting an empty input to fill when encountering {scope}, I'd get to pick one of those 3 values I just defined.

If no values are defined for a variable, simply prompt the original input for entering free text.

This would make this extension an obvious choice:

- all settings are directly in settings.json (no extra file for config
- you customize your own prompts according to your messageTemplate (your own workflow)
- easy selection with your own customized values (no need to type and thus avoid mistakes)

**Comment by rioukkevin** [comment]
Hi, Sorry for delay, thanks for all details, that's a very good Idea I work on in early January  😉

**Comment by rioukkevin** [comment]
It take a bit more time than I think to develop, I don't have full time on it, so, I promise it's in the next version but more on early February 🤭

**Comment by rioukkevin** [comment]
Sorry, it take a lot of time, lot more than i was thinking but I publish a new version (2.0.0) you can use it now ;)
