### ISSUE TITLE
Feature request: preview of file list

### ISSUE THREAD

**Issue by diogo-rossi** [rioukkevin/vscode-git-commit#8]
Using the template on the figure bellow, you get a prompt to fill with some information.
One of these information are the files that are being committed. 

Is it possible to identify the already staged files when prompt for "{files}",
giving you a preview list that could be edited?

This would speedup the commit message!

![image](https://user-images.githubusercontent.com/57204023/110327459-c3e34300-7ff8-11eb-88c6-f078cbbfd122.png)

**Comment by rioukkevin** [comment]
Hmm thinking about the how, I add tag WIP when start working on ;)

**Comment by rioukkevin** [comment]
It looks like it's difficult to get file list, I continue working on for 2.0.1

**Comment by rioukkevin** [comment]
I publish a new version, the feature is not in, but the code is prepared for this 😉

**Comment by m3koenig** [comment]
This is what I was looking for!
My current schema is "{prefix}: {editedFile}, {message}" (if its only in one file).
Would be cool if it gets the files or (at least?) the file im in :D

**Comment by rioukkevin** [comment]
I'm on a big update including files list and an UI to generate configuration for extension, I make a comment here when i deploy the new version

**Comment by rioukkevin** [comment]
you can get a preview of the configuration UI at [GCM config](https://gcm-config.netlify.app/) predefined values are missing (including files)

**Comment by rioukkevin** [comment]
Hi, I'm on a bug with this feature, it's the only thing missing for next version 😉

**Comment by rioukkevin** [comment]
Hi,

You can now get files list with the extension fell free to look at possibilities on doc https://gcm-config.netlify.app

PS: I deploy a new version (3.0.0) minutes ago

Have a nice day and be happy

**Comment by m3koenig** [comment]
Hi, thanks for that update! :)
But could you add an example for the files? I do not know how to add them :/

I tried some of those kind of configs:

```json
"vscodeGitCommit.template": [
        "{prefix}: {message}",
        "{files}"
    ],
    "vscodeGitCommit.variables": {
        "MaKo": [
            {
                "label": "🛠️Changed"
            },
            {
                "label": "⚙️Refactored"
            },
            {
                "label": "➕Added"
            },
            {
                "label": "❌Removed"
            },
            {
                "label": "\r\n📑",
                "detail": "Add an File Text"
            }
        ],
        "prefix": "MaKo...keke"
    }
```

**Comment by m3koenig** [comment]
oh...now I have found out:

```JSON
"vscodeGitCommit.template": [
        "{prefix}: {message} {files}"
    ],
    "vscodeGitCommit.variables": {
        "prefix": "MaKo...keke",
        "files": "files",
        "MaKo": [
            {
                "label": "🛠️Changed"
            },
            {
                "label": "⚙️Refactored"
            },
            {
                "label": "➕Added"
            },
            {
                "label": "❌Removed"
            },
            {
                "label": "\r\n📑",
                "detail": "Add an File Text"
            }
        ]
    }
  ```
  Thats realy cool! :) I like that!
  But is there a possibility only to add the file name and not the whole path? that would be great :)

**Comment by rioukkevin** [comment]
Hi, 

No problem, Glad you found the solution 😉 
I add it as a feature request for next updates

Thanks for your feedback
